// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsdmbfkxhcqhuheyaeoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzZG1iZmt4aGNxaHVoZXlhZW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODY4MjYsImV4cCI6MjA2MzY2MjgyNn0.jJEMJpE2M2j5Qc4VNHegchX1EZRAgtGfr_1H7_NNR18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);